<?php 


define("DB_HOST", "localhost");  //cambiar por el host de la base de datos
define("DB_USER", "gomosoft");  //cambiar por el usuario de la base de datos
define("DB_PASS", "p455wd"); //cambiar por la clave de la base de datos
define("DB_DB", "salas");
define("TIME_ZONE", "America/Bogota");
define("PATH","/");
define("domain","localhost");
define("APP_NAME","Salas");
define("APP_VERSION","v0.1 Beta");